clone:
  depth: full

pipelines:
  default:
    - step:
        image: node:8.6.0
        caches:
          - node
        script:         
          - npm install
          - npm run pipelines
          # Deploy to digital ocean
          - mkdir -p ~/.ssh          
          - cat my_known_hosts >> ~/.ssh/known_hosts          
          - (umask 077; echo $SSH_PRIVATE_KEY | base64 --decode -i > ~/.ssh/id_rsa)
          - git remote add server $DOCEAN_GIT_REPO
          - git push server master
        services:
          - postgres
definitions: 
  services: 
    postgres: 
      image: postgres
      environment: 
        POSTGRES_DB: 'pipelines' 
        POSTGRES_USER: 'test_user'
        POSTGRES_PASSWORD: 'test_user_password'
ssh://vinipachecov@138.197.10.233/var/repo/graphql-blog-api-git